spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

  jackson:
    serialization:
      indent_output: true
  jpa:
    hibernate.ddl-auto: update
    generate.ddl: true
    show-sql: true




